### ISSUE TITLE
[Challenge] 챌린지 카테고리 / 목록 / 상세 구현

### ISSUE THREAD

**Issue by plashdof** [CapstoneAOZTG/greengrim-android#18]
## TODO
- [x] 챌린지 카테고리 화면 구현
- [x] 챌린지 목록 화면 구현
- [x] 챌린지 상세 화면 구현

## DONE
- [x] 챌린지 카테고리 화면 구현
- [x] 챌린지 목록 화면 구현
  - [x] 챌린지 목록 BottomSheet 구현 
- [x] 챌린지 상세 화면 구현
  - [x] 챌린지 상세 PopupMenu 구현
- [x] Home Chip 레이아웃 변경
- [x] Home Indicator 구현
