### ISSUE TITLE
[Global] 전역 에러, 미구현 정리

### ISSUE THREAD

**Issue by plashdof** [CapstoneAOZTG/greengrim-android#44]
## Errors
- [x] MyCertification 달력 date 표시 리팩토링
- [x] CertificationDetail -> MyCertification 돌아왔을때, 이전 selectedDate 보관하기
- [x] ChatRoom 팝업 메뉴, 다른곳 클릭해도 안사라짐 에러 fix
- [x] ChatCertificationList Recyclerview 스크롤 에러 fix
- [x]  Challenge 생성하기 글자수 제한 걸기

## TODO
- [x] CertificationDetail 뒤로가기 로직 구현
- [x] MyCertification 뒤로가기 로직 구현
- [x] ChallengeDetail 이미 입장한 방이면, 입장하기 버튼 비활성화 (API 추가구현 대기중)
- [x] ChatCertificationList 월별 인증 date list API 연결
- [x] ChatCertificationList 날짜별 인증 list API 연결
- [x] 출석체크 구현, API 연결
