### ISSUE TITLE
[Refactor] 통신 로딩처리, 컨밴션 수정

### ISSUE THREAD

**Issue by plashdof** [CapstoneAOZTG/greengrim-android#48]
## TODO
- [ ] API 통신중 Loading 처리
- [ ] API 통신후, 데이터 Binding 안보이게 하기
- [ ] 네이밍 컨밴션 리팩토링, 획일화
- [ ] 디테일 수정
